language: node_js
node_js: node
env:
- NODE_ENV=test
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: NFmEa23SLqRtt73tyPk+Bb61S5+ADisOSlckmaVnS/yTrUNJr9ylo8uTaMzTYHx0uMz7RBosb8pP2wAvVffQPLQe8h320989eD1B1pvaNq3f8HDyIkZCwdh9oZuv3YbNzA8f+ki/sN2Nnm3DyNY7lE3EwFtARwZXCRLiasNAjTrjTl+8Mkk5eQNMDMpePGp29oKXZZQi5Sn6ZB6gqKhUuUTDkvUW5A/nKbbWM9bHYMwtVhQxkbafpJNuPUEyGJ876oqEmAhe6Vj2x5RWnXeq3paAKC9fFuH0cMO9bEIK+P/cvUCPtbxfrGVwsYtsjLW2fvsWwgIrfvAJrZNgodJP/FFn33TawEe/peQk5GTlD3YK6gTKuWrNE/mU5ePki88mjZPam3jN1it3gOQWale1mm8Th1UfzOyj9kRWK25htavmlxKsAXkIMmUhQgGA8k4TWMKXt9yu0syxOIOjPmIpitiFVyCS71/U+ki7ZAvRE0+z1CuvATX8CFkIbPVL2IKP8ETnDEJW2TR+th85TNBwBmBgQOjGa2nOIrlB6LYAvGErw0RY0mgASXQfHbLJE1ZfAYWGmwypMKEstbQ+vPv1FZF82uGQewiynDpmKJNDo8ZO9hiqw6cLlWHnMYL1Lry5WAnDXoNI+ugQOG+j4VlUjphYTVfIwPXevRGZ2AFdZXo=
  app: chris-noteful-v4
  on:
    repo: thinkful-ei19/chris-noteful-v4
