language: node_js
node_js: node
env:
- NODE_ENV=test
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: mxZw9B4RCeNHFjv+C5EYgskUHJFxn13uwK01G6NNeNt/SBXnDKjj/v5kEJvO4+PQBmAV7tsYk2t1WN1tY1gNFCL2W1yrB1ytN0DlhMpRHLFuP8rbuh+3l3V9yojFHLnkaPPEJfAhfotm81+rkR8R46X//Z6cDcGpW3Zj73WK+yZkieQK16wycvfrg+Go+9fDLLg5cw62WzQ7OZszGt2fUE8Nwj3kLZxHe4bUc4yYglxNJ71qojIASde2G5ezF3HscA84GFd2IzVHz3LLZ7IFFMAcrSb+0V8z1NsHJizPcO2R7hViK6rL6eN0NL3wIsdz2dnWdX3rZL0ZQ53tIqOhyl3OoKxHT/CwQBQJxWStawHrYLXD1GdDxa4RU28xRSInR9432I6MyRn8KpLYLLv6J27jlDgxANX4SLPqjrpSB2evl9bOtBrIlYSOuv0mmTcGDhiALmNs9yOoZ9YwGERlZlZi+SWyPbFtMdyJk042T/lbQU8ApamFbCH4lFavGpTUhjELxE0dVYrsG6uVYzWiNEdp2SwmiL6h3t377em78KEcr2Go/7g0WyLcTaNSrAO0uXbWqFvAIrjVWMSRV5ZCNn1iQitT5nYyqzacjlrxrckZqhC7ocS+9VOkyxlLPqi9NWaf8cwIztMtxMiRggl0I9nG/vV3cOaovab2ao3zRBg=
  app: chris-noteful-v3a
  on:
    repo: thinkful-ei19/chris-noteful-v4
